import React, { useEffect, useState } from 'react';
import { ArrowLeft, Boxes, CheckCircle2, LayoutDashboard, LogIn, Package, Plus, PlusCircle, Search, Settings, ShoppingCart, Star, Trash2, UserPlus, Users, X, Zap } from 'lucide-react';
import './App.css';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';
const demoProducts = [
  { id: 'demo-1', title: 'Smart 4K TV 55"', price: 599.99, description: 'Brilliant 4K picture quality with a simple smart interface for all your favorite streaming.', image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800', category: 'electronics', rating: { rate: 4.7, count: 234 } },
  { id: 'demo-2', title: 'Designer Silk Shirt', price: 79.99, description: 'Luxurious silk fabric with a modern cut, made for polished everyday dressing.', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800', category: "men's clothing", rating: { rate: 4.8, count: 342 } },
  { id: 'demo-3', title: 'Elegant Pleated Skirt', price: 59.99, description: 'A timeless pleated silhouette in lightweight fabric that moves beautifully.', image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800', category: "women's clothing", rating: { rate: 4.6, count: 456 } },
  { id: 'demo-4', title: 'Premium Air Conditioner', price: 449.99, description: 'Quiet, energy-efficient cooling with smart temperature control.', image: 'https://images.unsplash.com/photo-1631545806609-319c4e3f4b0e?w=800', category: 'electronics', rating: { rate: 4.5, count: 189 } }
];

const App = () => {
  const [page, setPage] = useState('home');
  const [products, setProducts] = useState([]);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [cart, setCart] = useState([]);
  const [loading, setLoading] = useState(true);
  const [authMode, setAuthMode] = useState(null);
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('shophub_user') || 'null'));
  const [authError, setAuthError] = useState('');
  const [notice, setNotice] = useState('');

  useEffect(() => { loadProducts(); }, []);
  const loadProducts = async () => { try { const response = await fetch(`${API_URL}/products`); if (!response.ok) throw new Error(); const data = await response.json(); setProducts(data.length ? data : demoProducts); } catch { setProducts(demoProducts); } finally { setLoading(false); } };
  const addToCart = (product) => setCart((current) => { const existing = current.find((item) => item.id === product.id); return existing ? current.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }]; });
  const updateQuantity = (id, delta) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: Math.max(0, item.quantity + delta) } : item).filter((item) => item.quantity > 0));
  const handleAuth = async (event) => { event.preventDefault(); setAuthError(''); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch(`${API_URL}/auth/${authMode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); localStorage.setItem('shophub_token', data.token); localStorage.setItem('shophub_user', JSON.stringify(data.user)); setUser(data.user); setAuthMode(null); setNotice(`Welcome, ${data.user.name}.`); } catch (error) { setAuthError(error.message || 'Authentication failed.'); } };
  const logout = () => { localStorage.removeItem('shophub_token'); localStorage.removeItem('shophub_user'); setUser(null); setPage('home'); };

  const ProductCard = ({ product }) => <article className="product-card" onClick={() => { setSelectedProduct(product); setPage('product'); }}><div className="product-image-container"><img src={product.image} alt={product.title} className="product-image" /></div><p className="product-category">{product.category}</p><h3 className="product-title">{product.title}</h3><div className="product-rating"><Star size={16} fill="#f5b841" color="#f5b841" /><span>{product.rating?.rate || 4.5} <small>({product.rating?.count || 0})</small></span></div><div className="product-footer"><span className="product-price">${Number(product.price).toFixed(2)}</span><button className="add-to-cart-btn" aria-label={`Add ${product.title} to cart`} onClick={(event) => { event.stopPropagation(); addToCart(product); }}><Plus size={20} /></button></div></article>;
  const HomePage = () => <><section className="hero-section"><div className="hero-content"><p className="eyebrow">CURATED FOR EVERYDAY LIVING</p><h1 className="hero-title">Good things,<br /><em>well chosen.</em></h1><p className="hero-subtitle">Shop practical pieces, considered design, and small upgrades that make a difference.</p><button className="hero-btn" onClick={() => setPage('products')}>Explore collection <ArrowLeft size={18} className="arrow-right" /></button></div></section><section className="features-section"><div className="feature-card"><Zap size={27} /><div><h3>Quick dispatch</h3><p>Thoughtfully packed and on its way fast.</p></div></div><div className="feature-card"><Package size={27} /><div><h3>Quality first</h3><p>Products selected to last beyond the moment.</p></div></div><div className="feature-card"><CheckCircle2 size={27} /><div><h3>Simple returns</h3><p>A little more confidence at checkout.</p></div></div></section><section className="featured-section"><div className="section-heading"><div><p className="eyebrow">THE EDIT</p><h2 className="section-title">Featured products</h2></div><button className="text-button" onClick={() => setPage('products')}>View all <ArrowLeft size={16} className="arrow-right" /></button></div><div className="featured-grid">{products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section></>;
  const ProductsPage = () => <section className="products-section"><div className="section-heading"><div><p className="eyebrow">SHOPHUB COLLECTION</p><h1 className="section-title">All products</h1></div><span className="result-count">{products.length} items</span></div>{loading ? <div className="loading-container"><div className="spinner" /></div> : <div className="products-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div>}</section>;
  const ProductDetails = () => selectedProduct && <section className="product-details"><button className="back-button" onClick={() => setPage('products')}><ArrowLeft size={18} /> Back to products</button><div className="product-details-grid"><div className="product-details-image-container"><img src={selectedProduct.image} alt={selectedProduct.title} className="product-details-image" /></div><div className="product-details-info"><p className="eyebrow">{selectedProduct.category}</p><h1 className="product-details-title">{selectedProduct.title}</h1><div className="product-details-rating"><Star size={18} fill="#f5b841" color="#f5b841" /> {selectedProduct.rating?.rate || 4.5} <span>({selectedProduct.rating?.count || 0} reviews)</span></div><p className="product-description">{selectedProduct.description}</p><div className="product-purchase"><span className="product-details-price">${Number(selectedProduct.price).toFixed(2)}</span><button className="add-to-cart-large" onClick={() => addToCart(selectedProduct)}><ShoppingCart size={19} /> Add to cart</button></div></div></div></section>;
  const CartPage = () => { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0).toFixed(2); return <section className="cart-section"><p className="eyebrow">YOUR BAG</p><h1 className="section-title">Shopping cart</h1>{cart.length === 0 ? <div className="empty-cart"><ShoppingCart size={54} /><p>Your cart is waiting for something good.</p><button className="continue-shopping-btn" onClick={() => setPage('products')}>Continue shopping</button></div> : <div className="cart-grid"><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt={item.title} className="cart-item-image" /><div className="cart-item-details"><h3>{item.title}</h3><span>${Number(item.price).toFixed(2)}</span></div><div className="cart-item-actions"><button className="remove-btn" onClick={() => setCart((current) => current.filter((entry) => entry.id !== item.id))}><Trash2 size={18} /></button><div className="quantity-controls"><button className="quantity-btn" onClick={() => updateQuantity(item.id, -1)}>-</button><b>{item.quantity}</b><button className="quantity-btn" onClick={() => updateQuantity(item.id, 1)}>+</button></div></div></div>)}</div><aside className="cart-summary-card"><h2>Order summary</h2><div className="summary-row"><span>Subtotal</span><b>${total}</b></div><div className="summary-row"><span>Shipping</span><b>Free</b></div><hr /><div className="summary-total"><span>Total</span><b>${total}</b></div><button className="checkout-btn">Proceed to checkout</button></aside></div>}</section>; };

  return <div className="app-container"><nav className="navbar"><div className="navbar-content"><button className="logo" onClick={() => setPage('home')}>Shop<span>Hub</span></button><div className="nav-links"><button className={page === 'home' ? 'active' : ''} onClick={() => setPage('home')}>Home</button><button className={page === 'products' ? 'active' : ''} onClick={() => setPage('products')}>Shop</button>{user?.role === 'admin' && <button className={page === 'admin' ? 'active admin-link' : 'admin-link'} onClick={() => setPage('admin')}>Admin</button>}</div><div className="nav-actions">{user ? <button className="account-button" onClick={logout}><span>{user.name.charAt(0).toUpperCase()}</span> Log out</button> : <><button className="auth-link" onClick={() => { setAuthMode('login'); setAuthError(''); }}>Log in</button><button className="signup-button" onClick={() => { setAuthMode('signup'); setAuthError(''); }}><UserPlus size={16} /> Sign up</button></>}<button className="cart-button" onClick={() => setPage('cart')}><ShoppingCart size={20} />{cart.length > 0 && <span className="cart-badge">{cart.reduce((sum, item) => sum + item.quantity, 0)}</span>}</button></div></div></nav><main className="main-content">{notice && <div className="notice"><CheckCircle2 size={17} />{notice}<button onClick={() => setNotice('')}><X size={15} /></button></div>}{page === 'home' && <HomePage />}{page === 'products' && <ProductsPage />}{page === 'product' && <ProductDetails />}{page === 'cart' && <CartPage />}{page === 'admin' && user?.role === 'admin' && <AdminPage user={user} token={localStorage.getItem('shophub_token')} products={products} setProducts={setProducts} />}</main>{authMode && <AuthModal mode={authMode} setMode={setAuthMode} onSubmit={handleAuth} error={authError} />}</div>;
};

const AuthModal = ({ mode, setMode, onSubmit, error }) => <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setMode(null)}><div className="auth-modal"><button className="modal-close" onClick={() => setMode(null)}><X size={20} /></button><p className="eyebrow">SHOPHUB ACCOUNT</p><h2>{mode === 'login' ? 'Welcome back.' : 'Join ShopHub.'}</h2><p className="modal-subtitle">{mode === 'login' ? 'Sign in to keep your favorites close.' : 'Create an account for a smoother way to shop.'}</p><form onSubmit={onSubmit}>{mode === 'signup' && <label>Name<input name="name" placeholder="Your name" required /></label>}<label>Email<input name="email" type="email" placeholder="you@example.com" required /></label><label>Password<input name="password" type="password" placeholder="At least 6 characters" minLength="6" required /></label>{error && <p className="form-error">{error}</p>}<button className="auth-submit" type="submit">{mode === 'login' ? <><LogIn size={17} /> Log in</> : <><UserPlus size={17} /> Create account</>}</button></form><button className="switch-auth" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Need an account? Sign up' : 'Already have an account? Log in'}</button></div></div>;

const AdminPage = ({ user, token, products, setProducts }) => {
  const [section, setSection] = useState('overview');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const createProduct = async (event) => {
    event.preventDefault();
    setMessage('');
    setError('');
    const payload = Object.fromEntries(new FormData(event.currentTarget).entries());
    try {
      const response = await fetch(`${API_URL}/products`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ ...payload, price: Number(payload.price) }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.message);
      setProducts((current) => [data, ...current]);
      event.currentTarget.reset();
      setMessage('Product added to the catalog.');
      setSection('products');
    } catch (requestError) { setError(requestError.message || 'Unable to add product.'); }
  };

  const deleteProduct = async (id) => {
    try {
      const response = await fetch(`${API_URL}/products/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } });
      if (!response.ok) throw new Error();
      setProducts((current) => current.filter((product) => product._id !== id && product.id !== id));
      setMessage('Product removed from the catalog.');
    } catch { setError('Unable to delete product.'); }
  };

  const navItems = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard },
    { id: 'products', label: 'Products', icon: Boxes },
    { id: 'add', label: 'Add product', icon: PlusCircle },
    { id: 'customers', label: 'Customers', icon: Users },
    { id: 'settings', label: 'Settings', icon: Settings }
  ];

  const Overview = () => <div className="admin-overview"><div className="admin-welcome"><div><p className="eyebrow">CONTROL ROOM</p><h1>Good morning, {user.name.split(' ')[0]}.</h1><p>Your store at a glance. Keep the catalog fresh and customers moving.</p></div><button className="admin-primary-button" onClick={() => setSection('add')}><Plus size={17} /> Add product</button></div><div className="admin-metrics"><div><span>Catalog items</span><strong>{products.length}</strong><small>Live products</small></div><div><span>Average rating</span><strong>{products.length ? (products.reduce((sum, product) => sum + (product.rating?.rate || 4.5), 0) / products.length).toFixed(1) : '0.0'}</strong><small>Across your catalog</small></div><div><span>Low stock</span><strong>0</strong><small>All inventory healthy</small></div><div><span>Store status</span><strong className="status-live">Live</strong><small>API connected when online</small></div></div><div className="admin-overview-grid"><div className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT CATALOG</p><h2>Latest products</h2></div><button className="panel-link" onClick={() => setSection('products')}>View all</button></div>{products.slice(0, 4).map((product) => <AdminProductRow key={product._id || product.id} product={product} onDelete={deleteProduct} />)}</div><div className="admin-panel admin-shortcut"><p className="eyebrow">QUICK ACTION</p><h2>Bring something new to the shelf.</h2><p>Add a product with an image, price, category, and story customers can understand.</p><button className="admin-secondary-button" onClick={() => setSection('add')}><PlusCircle size={18} /> Create a listing</button></div></div></div>;

  const Products = () => <div className="admin-products-page"><div className="admin-page-heading"><div><p className="eyebrow">CATALOG MANAGEMENT</p><h1>Products</h1><p>Review and manage every item in your store.</p></div><button className="admin-primary-button" onClick={() => setSection('add')}><Plus size={17} /> Add product</button></div><div className="admin-toolbar"><div className="admin-search"><Search size={17} /><input placeholder="Search products" /></div><span>{products.length} items</span></div><div className="admin-products-table"><div className="admin-table-head"><span>Product</span><span>Category</span><span>Price</span><span>Rating</span><span>Action</span></div>{products.map((product) => <div className="admin-table-row" key={product._id || product.id}><div className="admin-product-name"><img src={product.image} alt="" /><strong>{product.title}</strong></div><span className="table-muted">{product.category}</span><strong>${Number(product.price).toFixed(2)}</strong><span className="table-rating"><Star size={14} fill="#f5b841" color="#f5b841" /> {product.rating?.rate || 4.5}</span>{product._id ? <button className="table-delete" onClick={() => deleteProduct(product._id)}><Trash2 size={16} /></button> : <span className="table-muted">Demo</span>}</div>)}</div></div>;

  const AddProduct = () => <div className="admin-add-page"><div className="admin-page-heading"><div><p className="eyebrow">CATALOG MANAGEMENT</p><h1>Add a product</h1><p>Give your next product a place in the collection.</p></div></div><form className="admin-form admin-form-wide" onSubmit={createProduct}><div className="form-heading"><Package size={21} /><h2>Product details</h2></div><div className="admin-form-columns"><div><label>Product name<input name="title" placeholder="e.g. Linen overshirt" required /></label><div className="form-row"><label>Price<input name="price" type="number" min="0" step="0.01" placeholder="0.00" required /></label><label>Category<input name="category" placeholder="fashion" required /></label></div><label>Image URL<input name="image" type="url" placeholder="https://..." required /></label></div><div><label>Description<textarea name="description" rows="8" placeholder="What makes this product special?" required /></label></div></div>{message && <p className="form-success">{message}</p>}{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="admin-secondary-button" onClick={() => setSection('products')}>Cancel</button><button className="admin-primary-button" type="submit"><Plus size={17} /> Publish product</button></div></form></div>;

  const PlaceholderPage = ({ title, icon: Icon }) => <div className="admin-placeholder"><Icon size={30} /><p className="eyebrow">COMING NEXT</p><h1>{title}</h1><p>This admin section is ready for its data workflow. Product management is live today.</p></div>;

  return <section className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span>SH</span><div><strong>ShopHub</strong><small>Admin workspace</small></div></div><nav className="admin-nav">{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? 'active' : ''} onClick={() => { setSection(id); setMessage(''); setError(''); }}><Icon size={18} />{label}</button>)}</nav><div className="admin-user"><div className="admin-avatar">{user.name.charAt(0).toUpperCase()}</div><div><strong>{user.name}</strong><small>Administrator</small></div></div></aside><div className="admin-workspace">{section === 'overview' && <Overview />}{section === 'products' && <Products />}{section === 'add' && <AddProduct />}{section === 'customers' && <PlaceholderPage title="Customers" icon={Users} />}{section === 'settings' && <PlaceholderPage title="Settings" icon={Settings} />}</div></section>;
};

const AdminProductRow = ({ product, onDelete }) => <div className="admin-product"><img src={product.image} alt="" /><div><strong>{product.title}</strong><span>${Number(product.price).toFixed(2)}</span></div>{product._id && <button className="remove-btn" onClick={() => onDelete(product._id)}><Trash2 size={17} /></button>}</div>;

export default App;